### ISSUE TITLE
is it possible to use "buffer" instead of "tabs"

### ISSUE THREAD

**Issue by yilinyang7** [esquires/lvdb#1]
Thanks for your great work, it's very helpful.
I wonder if it's possible to use buffers instead of tabs? I believe many vim people prefer buffers. 

Also, is it possible to always toggle debug mode? Since toggle on and off can be very forgettable.

Best.

**Comment by esquires** [comment]
No problem. I just pushed a fix to the latest master. It will only switch tabs when ``switchbuf`` is set to ``usetab`` or ``newtab``. To always be in debug mode you can call the following in your ``.vimrc``:
```
call lvdb#Python_debug()
```

Note that you probably also want to add ``let g:lvdb_silent = 1`` in this case.

**Comment by yilinyang7** [comment]
Thanks! Enjoy your fix :)
