### ISSUE TITLE
after "jump" command from ipdb, the position doesn't sync to vim

### ISSUE THREAD

**Issue by yilinyang7** [esquires/lvdb#2]
It's pretty nice to use generally. I just found this tiny bug that it doesn't work with "jump" command.

Best.

**Comment by yilinyang7** [comment]
Also, if possible, it would be nice if it works with "where" command to resync the position, since sometimes during debugging I just move around in vim.

**Comment by esquires** [comment]
Good suggestion. Both of these features are now on master.

**Comment by yilinyang7** [comment]
Thanks! It'd be better to also work with abbreviation "w"/"j".

**Comment by esquires** [comment]
No problem. I just pushed a fix.
